### ISSUE TITLE
Decoding Seaport Events (OrderFulfilled)

### ISSUE THREAD

**Issue by dsgriffin** [ProjectOpenSea/seaport#529]
We're trying to monitor event transactions directly and, in a similar way as we were for Wyvern, decode the event logs of a Seaport transaction.

Event signature: 

```event OrderFulfilled(bytes32 orderHash, address offerer, address zone, address recipient, struct SpentItem[] offer, struct ReceivedItem[] consideration)```

The new contract is using a couple of `Structs` for `offer` and `consideration`. How are we able to decode these structs for event monitoring? Neither of the following are working:

```
web3.eth.abi.decodeLog([{
    type: 'bytes32',
    name: 'orderHash',
  },
  {
    type: 'address',
    name: 'offerer',
  },
  {
    type: 'address',
    name: 'zone',
  },
  {
        type: 'address',
        name: 'recipient',
  },
  {
    type: '(uint8,address,uint256,uint256)[]',
        name: 'offer',
  },
  {
     type: '(uint8,address,uint256,uint256,address)[]',
     name: 'consideration',
   },
]
```

**Comment by callikai** [comment]
I made a little progress with the following, but was getting overflows from ethers... so not quite there

logDecoder: [
      {
        name: "orderHash",
        type: "bytes32",
      },
      {
        name: "offerer",
        type: "address",
      },
      {
        name: "zone",
        type: "address",
      },
      {
        name: "recipient",
        type: "address",
      },
      {
        name: "offer",
        type: "tuple[]",
        components: [
          {
            name: "itemType",
            type: "uint8",
          },
          {
            name: "token",
            type: "address",
          },
          {
            name: "identifier",
            type: "uint256",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
      },
      {
        name: "consideration",
        type: "tuple[]",
        components: [
          {
            name: "itemType",
            type: "uint8",
          },
          {
            name: "token",
            type: "address",
          },
          {
            name: "identifier",
            type: "uint256",
          },
          {
            name: "amount",
            type: "uint256",
          },
          {
            name: "recipient",
            type: "address",
          },
        ],
      },
    ]

**Comment by callikai** [comment]
I think I made a little progress with the below ABI, but haven't quite figured it out yet.
```logDecoder: [
      {
        name: "orderHash",
        type: "bytes32",
      },
      {
        name: "offerer",
        type: "address",
      },
      {
        name: "zone",
        type: "address",
      },
      {
        name: "recipient",
        type: "address",
      },
      {
        name: "offer",
        type: "tuple[]",
        components: [
          {
            name: "itemType",
            type: "uint8",
          },
          {
            name: "token",
            type: "address",
          },
          {
            name: "identifier",
            type: "uint256",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
      },
      {
        name: "consideration",
        type: "tuple[]",
        components: [
          {
            name: "itemType",
            type: "uint8",
          },
          {
            name: "token",
            type: "address",
          },
          {
            name: "identifier",
            type: "uint256",
          },
          {
            name: "amount",
            type: "uint256",
          },
          {
            name: "recipient",
            type: "address",
          },
        ],
      },
    ],```

**Comment by dsgriffin** [comment]
The above causes the following: 

```
2022-06-21T07:51:51.979518+00:00 app[worker.1]: /app/node_modules/web3-eth-abi/lib/index.js:297
2022-06-21T07:51:51.979541+00:00 app[worker.1]:         throw new Error('Returned values aren\'t valid, did it run Out of Gas? ' +
2022-06-21T07:51:51.979542+00:00 app[worker.1]:               ^
2022-06-21T07:51:51.979542+00:00 app[worker.1]: 
2022-06-21T07:51:51.979551+00:00 app[worker.1]: Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
2022-06-21T07:51:51.979552+00:00 app[worker.1]:     at ABICoder.decodeParametersWith (/app/node_modules/web3-eth-abi/lib/index.js:297:15)
2022-06-21T07:51:51.979552+00:00 app[worker.1]:     at ABICoder.decodeParameters (/app/node_modules/web3-eth-abi/lib/index.js:284:17)
2022-06-21T07:51:51.979552+00:00 app[worker.1]:     at ABICoder.decodeParameter (/app/node_modules/web3-eth-abi/lib/index.js:273:17)
2022-06-21T07:51:51.979553+00:00 app[worker.1]:     at /app/node_modules/web3-eth-abi/lib/index.js:341:25
2022-06-21T07:51:51.979553+00:00 app[worker.1]:     at Array.forEach (<anonymous>)
2022-06-21T07:51:51.979554+00:00 app[worker.1]:     at ABICoder.decodeLog (/app/node_modules/web3-eth-abi/lib/index.js:337:12)
2022-06-21T07:51:51.979555+00:00 app[worker.1]:     at Subscription.<anonymous> (/app/app.js:92:47)
2022-06-21T07:51:51.979555+00:00 app[worker.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by thezenvan** [comment]
@dsgriffin did you manage to solve this? I'm trying to decode a NFT sale event but can't figure how to
https://etherscan.io/tx/0xe0b9b25822b2adc8ae16d7ad8bec975a690df84d0ad9c16c9400ef3835b8146f#eventlog
